export const HOST_ADD_FILES = 'HOST_ADD_FILES';
export const HOST_REMOVE_FILE = 'HOST_REMOVE_FILE';
export const HOST_CLEAR_FILES = 'HOST_CLEAR_FILES';

export const CLIENT_ADD_FILES = 'CLIENT_ADD_FILES';
export const CLIENT_REMOVE_FILE = 'CLIENT_REMOVE_FILE';

export const SET_CONNECTION = 'SET_CONNECTION';
export const SET_CONNECTION_STATUS = 'SET_CONNECTION_STATUS';

export const SET_DOWNLOAD_PROGRESS = 'SET_DOWNLOAD_PROGRESS';
export const SAVE_FILE_DATA = 'SAVE_FILE_DATA';
