export const HOST_ADD_FILES = 'HOST_ADD_FILES';
export const HOST_REMOVE_FILE = 'HOST_REMOVE_FILE';

export const CLIENT_ADD_FILES = 'CLIENT_ADD_FILES';
export const CLIENT_REMOVE_FILE = 'CLIENT_REMOVE_FILE';

export const SET_CONNECTION = 'SET_CONNECTION';
